print("Second half action")
print("===============")
input("enter the home team half time score:")
input("enter the away team half time score:")
print()
input("enter the home team full time score")
input("enter the away team full time score")
print()
print("the total number of goals scored after halftime is:")